{% set version = "1.2.0.post0" %}

package:
  name: ratelimiter
  version: {{ version }}

source:
  fn: ratelimiter-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/ratelimiter/ratelimiter-{{ version }}.tar.gz
  sha256: 5c395dcabdbbde2e5178ef3f89b568a3066454a6ddc223b76473dac22f89b4f7

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python <3.11
    - setuptools
  run:
    - python <3.11

test:
  imports:
    - ratelimiter

about:
  home: https://github.com/RazerM/ratelimiter
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: Simple Python module providing rate limiting.
  description: |
    This package provides the ratelimiter module, which ensures that an operation
    will not be executed more than a given number of times on a given period.
    This can prove useful when working with third parties APIs which require
    for example a maximum of 10 requests per second.

extra:
  recipe-maintainers:
    - johanneskoester
